/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Community;
import models.Doctor;
import models.Hospital;
import models.Patient;
import models.Encounter;
import models.VitalSign;

/**
 *
 * @author sid
 */
public class MainFrame extends javax.swing.JFrame {
public ArrayList<Community> CommunityList = new ArrayList<Community>();
public ArrayList<Hospital> HospitalList = new ArrayList<Hospital>();
public ArrayList<Patient> PatientList;
public ArrayList<Encounter> EncounterList;
public ArrayList<Doctor> DoctorList = new ArrayList<Doctor>();

public Community comm = new Community();
public ArrayList<String> locations = new ArrayList<>();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        //loadData();
        locations = (ArrayList)comm.getList();
          //add combobox default values here
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        //model.addElement("Toronto");
        //model.addElement("Vancouver");
        model.addAll(locations);
        comboHospLoc.setModel(model);
        
        Community community1 = new Community(1 , "Toronto");
        Community community2 = new Community(2 , "Vancouver");
        CommunityList.add(community1);
        CommunityList.add(community2); 
        
        Doctor doctor1 = new Doctor(1, "Clark Kent", "Orthopedics");
        Doctor doctor2 = new Doctor(2, "Will Smith", "Cardiac");
    
        DoctorList.add(doctor1);
        DoctorList.add(doctor2);
      
        
        Hospital hospital1 = new Hospital(1, "Sancheti", "FC Road", CommunityList.get(0),DoctorList.get(0));
        Hospital hospital2 = new Hospital(2, "Ruby", "JMD", CommunityList.get(1),DoctorList.get(1));
        HospitalList.add(hospital1);
        HospitalList.add(hospital2);
        

      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        SplitPane = new javax.swing.JSplitPane();
        TopPanel = new javax.swing.JPanel();
        PatientView = new javax.swing.JButton();
        DoctorView = new javax.swing.JButton();
        AdminView = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        DoctorPanel = new javax.swing.JPanel();
        DocSplitPane = new javax.swing.JSplitPane();
        DocTopPanel = new javax.swing.JPanel();
        LabelDoctor = new javax.swing.JLabel();
        newPatientViewButton = new javax.swing.JButton();
        newEncounterButton = new javax.swing.JButton();
        viewPatientButton = new javax.swing.JButton();
        DocBotPanel = new javax.swing.JPanel();
        viewPatientPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewPatientsTable = new javax.swing.JTable();
        addPatientPanel = new javax.swing.JPanel();
        patientNameLabel = new javax.swing.JLabel();
        patientDobLabel = new javax.swing.JLabel();
        patientIdLabel = new javax.swing.JLabel();
        patientContactNoLabel = new javax.swing.JLabel();
        patientNameField = new javax.swing.JTextField();
        patientIdField = new javax.swing.JTextField();
        patientContactNoField = new javax.swing.JTextField();
        patientDobField = new com.toedter.calendar.JDateChooser();
        addPatientButton = new javax.swing.JButton();
        newPatientError = new javax.swing.JLabel();
        addEncounterPanel = new javax.swing.JPanel();
        encounterDateLabel = new javax.swing.JLabel();
        encounterVitalSignLabel = new javax.swing.JLabel();
        diagnosisLabel = new javax.swing.JLabel();
        encounterHeartField = new javax.swing.JTextField();
        encounterHeartRateLabel = new javax.swing.JLabel();
        encounterBloodPressureLabel = new javax.swing.JLabel();
        encounterTemperatureLabel = new javax.swing.JLabel();
        encounterRespiratoryRateLabel = new javax.swing.JLabel();
        encounterPatientLabel = new javax.swing.JLabel();
        encounterPatientIdField = new javax.swing.JTextField();
        EncounterBloodField = new javax.swing.JTextField();
        encounterTemperatureField = new javax.swing.JTextField();
        encounterRespField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        encounterDiagnosisField = new javax.swing.JTextArea();
        encounterDateField = new com.toedter.calendar.JDateChooser();
        addEncounterButton = new javax.swing.JButton();
        errorEncounter = new javax.swing.JLabel();
        PatientPanel = new javax.swing.JPanel();
        NearbyLabel = new javax.swing.JLabel();
        HospitalTable = new javax.swing.JScrollPane();
        HospitalDetails = new javax.swing.JTable();
        locationLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        comboHospLoc = new javax.swing.JComboBox<>();
        AdminPanel = new javax.swing.JPanel();
        LabelAdmin = new javax.swing.JLabel();
        TextCommunity = new javax.swing.JTextField();
        LabelCommunity = new javax.swing.JLabel();
        ButtonCommunity = new javax.swing.JButton();
        LabelHospName = new javax.swing.JLabel();
        TextHospName = new javax.swing.JTextField();
        LabelHospLoc = new javax.swing.JLabel();
        TextHospLoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextHospComm = new javax.swing.JTextField();
        ButtonAddHosp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        errorAdmin = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        PatientView.setText("Patient");

        DoctorView.setText("Doctor");

        AdminView.setText("Admin");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(PatientView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(DoctorView, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(AdminView, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientView)
                    .addComponent(DoctorView)
                    .addComponent(AdminView))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        SplitPane.setTopComponent(TopPanel);

        BottomPanel.setLayout(new java.awt.CardLayout());

        DocSplitPane.setDividerLocation(300);
        DocSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        DocTopPanel.setBackground(new java.awt.Color(204, 255, 255));

        LabelDoctor.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelDoctor.setText("Doctor Panel");

        newPatientViewButton.setText("Add new Patient");
        newPatientViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPatientViewButtonActionPerformed(evt);
            }
        });

        newEncounterButton.setText("Add new Encounter");

        viewPatientButton.setText("View Patient Details");

        javax.swing.GroupLayout DocTopPanelLayout = new javax.swing.GroupLayout(DocTopPanel);
        DocTopPanel.setLayout(DocTopPanelLayout);
        DocTopPanelLayout.setHorizontalGroup(
            DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocTopPanelLayout.createSequentialGroup()
                .addGroup(DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DocTopPanelLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(LabelDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DocTopPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(newPatientViewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(newEncounterButton)
                        .addGap(66, 66, 66)))
                .addComponent(viewPatientButton)
                .addGap(148, 148, 148))
        );
        DocTopPanelLayout.setVerticalGroup(
            DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocTopPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelDoctor)
                .addGap(7, 7, 7)
                .addGroup(DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPatientViewButton)
                    .addComponent(newEncounterButton)
                    .addComponent(viewPatientButton))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        DocSplitPane.setTopComponent(DocTopPanel);

        DocBotPanel.setLayout(new java.awt.CardLayout());

        viewPatientPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                viewPatientPanelFocusGained(evt);
            }
        });

        viewPatientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Date Of Birth", "Contact No", "Update", "Delete"
            }
        ));
        jScrollPane2.setViewportView(viewPatientsTable);

        javax.swing.GroupLayout viewPatientPanelLayout = new javax.swing.GroupLayout(viewPatientPanel);
        viewPatientPanel.setLayout(viewPatientPanelLayout);
        viewPatientPanelLayout.setHorizontalGroup(
            viewPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPatientPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        viewPatientPanelLayout.setVerticalGroup(
            viewPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPatientPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        DocBotPanel.add(viewPatientPanel, "card4");

        patientNameLabel.setText("Name");

        patientDobLabel.setText("Date Of Birth");

        patientIdLabel.setText("Patient Id");

        patientContactNoLabel.setText("Contact No");

        patientNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                patientNameFieldFocusLost(evt);
            }
        });

        patientIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                patientIdFieldFocusLost(evt);
            }
        });
        patientIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdFieldActionPerformed(evt);
            }
        });

        patientContactNoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                patientContactNoFieldFocusLost(evt);
            }
        });

        patientDobField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                patientDobFieldFocusLost(evt);
            }
        });

        addPatientButton.setText("Add New Patient");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        newPatientError.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout addPatientPanelLayout = new javax.swing.GroupLayout(addPatientPanel);
        addPatientPanel.setLayout(addPatientPanelLayout);
        addPatientPanelLayout.setHorizontalGroup(
            addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientPanelLayout.createSequentialGroup()
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPatientPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientIdLabel)
                            .addComponent(patientNameLabel)
                            .addComponent(patientDobLabel)
                            .addComponent(patientContactNoLabel))
                        .addGap(26, 26, 26)
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientDobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPatientError)))
                    .addGroup(addPatientPanelLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(addPatientButton)))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        addPatientPanelLayout.setVerticalGroup(
            addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdLabel)
                    .addComponent(patientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNameLabel))
                .addGap(40, 40, 40)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientDobLabel)
                    .addComponent(patientDobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientContactNoLabel)
                    .addComponent(patientContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(newPatientError)
                .addGap(18, 18, 18)
                .addComponent(addPatientButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        DocBotPanel.add(addPatientPanel, "card2");

        encounterDateLabel.setText("Date:");

        encounterVitalSignLabel.setText("Vital Sign:");

        diagnosisLabel.setText("Diagnosis:");

        encounterHeartField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                encounterHeartFieldFocusLost(evt);
            }
        });

        encounterHeartRateLabel.setText("HeartRate:");

        encounterBloodPressureLabel.setText("BloodPressure:");

        encounterTemperatureLabel.setText("Temperature:");

        encounterRespiratoryRateLabel.setText("Respiratory Rate:");

        encounterPatientLabel.setText("Patient Id:");

        encounterPatientIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                encounterPatientIdFieldFocusLost(evt);
            }
        });

        EncounterBloodField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EncounterBloodFieldFocusLost(evt);
            }
        });

        encounterTemperatureField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                encounterTemperatureFieldFocusLost(evt);
            }
        });

        encounterRespField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                encounterRespFieldFocusLost(evt);
            }
        });

        encounterDiagnosisField.setColumns(20);
        encounterDiagnosisField.setRows(5);
        encounterDiagnosisField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                encounterDiagnosisFieldFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(encounterDiagnosisField);

        encounterDateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                encounterDateFieldFocusLost(evt);
            }
        });

        addEncounterButton.setText("Add Encounter");
        addEncounterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEncounterButtonActionPerformed(evt);
            }
        });

        errorEncounter.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout addEncounterPanelLayout = new javax.swing.GroupLayout(addEncounterPanel);
        addEncounterPanel.setLayout(addEncounterPanelLayout);
        addEncounterPanelLayout.setHorizontalGroup(
            addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEncounterPanelLayout.createSequentialGroup()
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEncounterPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEncounterPanelLayout.createSequentialGroup()
                                .addComponent(diagnosisLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEncounterPanelLayout.createSequentialGroup()
                                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encounterPatientLabel)
                                    .addComponent(encounterDateLabel)
                                    .addComponent(encounterVitalSignLabel))
                                .addGap(35, 35, 35)
                                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encounterDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(encounterPatientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(addEncounterPanelLayout.createSequentialGroup()
                        .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addEncounterPanelLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encounterHeartRateLabel)
                                    .addComponent(encounterBloodPressureLabel)
                                    .addComponent(encounterTemperatureLabel))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEncounterPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(encounterRespiratoryRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(encounterTemperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EncounterBloodField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encounterRespField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addEncounterPanelLayout.createSequentialGroup()
                                .addComponent(encounterHeartField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                                .addComponent(errorEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addEncounterPanelLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(addEncounterButton)))
                .addGap(123, 123, 123))
        );
        addEncounterPanelLayout.setVerticalGroup(
            addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEncounterPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterPatientLabel)
                    .addComponent(encounterPatientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encounterDateLabel)
                    .addComponent(encounterDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(encounterVitalSignLabel)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEncounterPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(encounterHeartRateLabel)
                            .addComponent(encounterHeartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEncounterPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(errorEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterBloodPressureLabel)
                    .addComponent(EncounterBloodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterTemperatureLabel)
                    .addComponent(encounterTemperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterRespiratoryRateLabel)
                    .addComponent(encounterRespField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diagnosisLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(addEncounterButton))
        );

        DocBotPanel.add(addEncounterPanel, "card3");

        DocSplitPane.setRightComponent(DocBotPanel);

        javax.swing.GroupLayout DoctorPanelLayout = new javax.swing.GroupLayout(DoctorPanel);
        DoctorPanel.setLayout(DoctorPanelLayout);
        DoctorPanelLayout.setHorizontalGroup(
            DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DocSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        DoctorPanelLayout.setVerticalGroup(
            DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DocSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        BottomPanel.add(DoctorPanel, "card3");

        NearbyLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        NearbyLabel.setText("Nearby Hospitals");

        HospitalDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Community", "Doctor"
            }
        ));
        HospitalTable.setViewportView(HospitalDetails);

        locationLabel.setText("Select Location :");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        error.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout PatientPanelLayout = new javax.swing.GroupLayout(PatientPanel);
        PatientPanel.setLayout(PatientPanelLayout);
        PatientPanelLayout.setHorizontalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
            .addGroup(PatientPanelLayout.createSequentialGroup()
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(NearbyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(HospitalTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(locationLabel)
                        .addGap(30, 30, 30)
                        .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboHospLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        PatientPanelLayout.setVerticalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NearbyLabel)
                .addGap(54, 54, 54)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(comboHospLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(searchButton)
                .addGap(120, 120, 120)
                .addComponent(HospitalTable, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        BottomPanel.add(PatientPanel, "card2");

        LabelAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelAdmin.setText("Admin Controls");

        TextCommunity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextCommunityFocusLost(evt);
            }
        });

        LabelCommunity.setText("Community Name");

        ButtonCommunity.setText("Add Community");
        ButtonCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCommunityActionPerformed(evt);
            }
        });

        LabelHospName.setText("Hospital Name");

        TextHospName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextHospNameFocusLost(evt);
            }
        });

        LabelHospLoc.setText("Hospital Location");

        TextHospLoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextHospLocFocusLost(evt);
            }
        });

        jLabel2.setText("Hospital Community");

        TextHospComm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextHospCommFocusLost(evt);
            }
        });

        ButtonAddHosp.setText("Add Hospital");
        ButtonAddHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddHospActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Location", "Hospital Community", "Modify"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        errorAdmin.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(LabelAdmin))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextCommunity)
                                    .addComponent(LabelCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                .addGap(89, 89, 89)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelHospLoc)
                                    .addComponent(jLabel2)
                                    .addComponent(LabelHospName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextHospName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextHospComm, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextHospLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                        .addComponent(errorAdmin)
                        .addGap(520, 520, 520))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                        .addComponent(ButtonAddHosp)
                        .addGap(244, 244, 244))))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAdmin)
                .addGap(30, 30, 30)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCommunity)
                    .addComponent(LabelHospName)
                    .addComponent(TextHospName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelHospLoc)
                    .addComponent(TextHospLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ButtonCommunity))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextHospComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addComponent(errorAdmin)
                .addGap(36, 36, 36)
                .addComponent(ButtonAddHosp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        BottomPanel.add(AdminPanel, "card4");

        SplitPane.setRightComponent(BottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //private void loadData()
    //{
      //  DefaultComboBoxModel model = new DefaultComboBoxModel();
        //        model.addElement(new Community("1","Toronto"));
        //      model.addElement(new Community("2","Vancouver"));
        //        comboHospLoc.setModel(model);
    //}
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
       Integer selectedLocation = comboHospLoc.getSelectedIndex();
       DefaultTableModel model = (DefaultTableModel)HospitalDetails.getModel();
        model.setRowCount(0);
       Object rowData[] = new Object[4]; 
      

               
              
      
        
       
        for(int i = 0; i < HospitalList.size(); i++)
        {
            
        if(HospitalList.get(i).getCommunity().getName().contains(comboHospLoc.getSelectedItem().toString()))
        { rowData[0] = HospitalList.get(i).getName();
        rowData[1] = HospitalList.get(i).getLocation();
        rowData[2] = HospitalList.get(i).getCommunity().getName();
        rowData[3] = HospitalList.get(i).getDoctor().getName();
         model.addRow(rowData);}
        }
     
       
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void patientIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdFieldActionPerformed

    private void newPatientViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPatientViewButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPatientViewButtonActionPerformed

    private void patientIdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patientIdFieldFocusLost
        // TODO add your handling code here:
        if(!patientIdField.getText().matches("^[0-9]*$") || patientIdField.getText().length()!=2){
        newPatientError.setText("Please check the entered value");}
    }//GEN-LAST:event_patientIdFieldFocusLost

    private void patientNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patientNameFieldFocusLost
        // TODO add your handling code here:
        if(!patientNameField.getText().matches("[a-zA-Z]+") || patientNameField.getText().isEmpty()){
        newPatientError.setText("Please check the entered value");}
    }//GEN-LAST:event_patientNameFieldFocusLost

    private void patientDobFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patientDobFieldFocusLost
        // TODO add your handling code here:
        if(patientDobField.getDate().toString().isEmpty()){
        newPatientError.setText("Please check the entered value");
        }
    }//GEN-LAST:event_patientDobFieldFocusLost

    private void patientContactNoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patientContactNoFieldFocusLost
        // TODO add your handling code here:
        if(!patientContactNoField.getText().matches("^[0-9]*$") && patientContactNoField.getText().length ()!=10){
        newPatientError.setText("Please check the entered value");
        }
    }//GEN-LAST:event_patientContactNoFieldFocusLost

    private void encounterPatientIdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encounterPatientIdFieldFocusLost
        // TODO add your handling code here:
        if(!encounterPatientIdField.getText().matches("^[0-9]*$") || encounterPatientIdField.getText().length()!=2){
        errorEncounter.setText("Please check the entered value");}
    }//GEN-LAST:event_encounterPatientIdFieldFocusLost

    private void encounterDateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encounterDateFieldFocusLost
        // TODO add your handling code here:
        if(encounterDateField.getDate().toString().isEmpty()){
        errorEncounter.setText("Please check the entered value");
        }
    }//GEN-LAST:event_encounterDateFieldFocusLost

    private void encounterHeartFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encounterHeartFieldFocusLost
        // TODO add your handling code here:
        if(!encounterHeartField.getText().matches("^[0-9]*$") || encounterHeartField.getText().length()>=3 && encounterHeartField.getText().length()<=2){
       errorEncounter.setText("Please check the entered value");}
    }//GEN-LAST:event_encounterHeartFieldFocusLost

    private void EncounterBloodFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EncounterBloodFieldFocusLost
        // TODO add your handling code here:
        if(!EncounterBloodField.getText().matches("^[0-9]*$") || EncounterBloodField.getText().length()!=2){
        errorEncounter.setText("Please check the entered value");}
    }//GEN-LAST:event_EncounterBloodFieldFocusLost

    private void encounterTemperatureFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encounterTemperatureFieldFocusLost
        // TODO add your handling code here:
        if(!encounterTemperatureField.getText().matches("^[0-9]*$") || encounterTemperatureField.getText().length()!=2){
        errorEncounter.setText("Please check the entered value");}
    }//GEN-LAST:event_encounterTemperatureFieldFocusLost

    private void encounterRespFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encounterRespFieldFocusLost
        // TODO add your handling code here:
        if(!encounterRespField.getText().matches("^[0-9]*$") || encounterRespField.getText().length()!=2){
        errorEncounter.setText("Please check the entered value");}
    }//GEN-LAST:event_encounterRespFieldFocusLost

    private void encounterDiagnosisFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encounterDiagnosisFieldFocusLost
        // TODO add your handling code here:
        if(encounterDiagnosisField.getText().isEmpty()){
        errorEncounter.setText("Please check the entered value");
        }
    }//GEN-LAST:event_encounterDiagnosisFieldFocusLost

    private void TextCommunityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextCommunityFocusLost
        // TODO add your handling code here:
        if(!TextCommunity.getText().matches("[a-zA-Z]+") || TextCommunity.getText().isEmpty()){
        errorAdmin.setText("Please check the entered value");
        }
    }//GEN-LAST:event_TextCommunityFocusLost

    private void TextHospNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextHospNameFocusLost
        // TODO add your handling code here:
        if(!TextHospName.getText().matches("[a-zA-Z]+") || TextHospName.getText().isEmpty()){
        errorAdmin.setText("Please check the entered value");}
    }//GEN-LAST:event_TextHospNameFocusLost

    private void TextHospLocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextHospLocFocusLost
        // TODO add your handling code here:
        if(!TextHospLoc.getText().matches("[a-zA-Z]+") || TextHospLoc.getText().isEmpty()){
        errorAdmin.setText("Please check the entered value");}
    }//GEN-LAST:event_TextHospLocFocusLost

    private void TextHospCommFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextHospCommFocusLost
        // TODO add your handling code here:
        if(!TextHospComm.getText().matches("[a-zA-Z]+") || TextHospComm.getText().isEmpty()){
        errorAdmin.setText("Please check the entered value");}
    }//GEN-LAST:event_TextHospCommFocusLost

    private void ButtonCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCommunityActionPerformed
        // TODO add your handling code here:
        Community community1 = new Community(1 , "Toronto");
        Community community2 = new Community(2 , "Vancouver");
        CommunityList.add(community1);
        CommunityList.add(community2);
        CommunityList.add(new Community(3 , TextCommunity.getText()));
    }//GEN-LAST:event_ButtonCommunityActionPerformed

    private void ButtonAddHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddHospActionPerformed
        // TODO add your handling code here:

       HospitalList.add(new Hospital(3, TextHospName.getText(), TextHospLoc.getText(), CommunityList.get(0), DoctorList.get(0)));
     
    }//GEN-LAST:event_ButtonAddHospActionPerformed

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        // TODO add your handling code here:
        Patient patient = new Patient(1, "Rob" , "22-08-2019" , "7878787878");
        PatientList.add(1, patient);
        PatientList.add(new Patient(Integer.parseInt(patientIdField.getText()), patientNameField.getText(),patientDobField.getDateFormatString(),patientContactNoField.getText()));
        
        // Display Patients
        DefaultTableModel patientModel = new DefaultTableModel();
        
         patientModel.setRowCount(0);
       Object rowData[] = new Object[6]; 
       
        for(int i = 0; i < PatientList.size(); i++)
        {
     
         rowData[0] = PatientList.get(i).getPatientID();
        rowData[1] = PatientList.get(i).getName();
        rowData[2] = PatientList.get(i).getDob();
        rowData[3] = PatientList.get(i).getContactNumber();
        rowData[4] = new JButton("Update");
        rowData[5] = new JButton("Delete");
         patientModel.addRow(rowData);}

        
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void addEncounterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEncounterButtonActionPerformed
        // TODO add your handling code here:
        Encounter encounter1 = new Encounter(1, LocalDate.now(), PatientList.get(0), new VitalSign(1, 76, 65, 77, 98) , "All good!");
        EncounterList.add(encounter1);
        EncounterList.add(new Encounter(2, LocalDate.now(), PatientList.get(0), new VitalSign(1, 56, 95, 67, 78), encounterDiagnosisField.getText()));
       
    }//GEN-LAST:event_addEncounterButtonActionPerformed

    private void viewPatientPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viewPatientPanelFocusGained

        // TODO add your handling code here:
     
    }//GEN-LAST:event_viewPatientPanelFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
              
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JButton AdminView;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton ButtonAddHosp;
    private javax.swing.JButton ButtonCommunity;
    private javax.swing.JPanel DocBotPanel;
    private javax.swing.JSplitPane DocSplitPane;
    private javax.swing.JPanel DocTopPanel;
    private javax.swing.JPanel DoctorPanel;
    private javax.swing.JButton DoctorView;
    private javax.swing.JTextField EncounterBloodField;
    private javax.swing.JTable HospitalDetails;
    private javax.swing.JScrollPane HospitalTable;
    private javax.swing.JLabel LabelAdmin;
    private javax.swing.JLabel LabelCommunity;
    private javax.swing.JLabel LabelDoctor;
    private javax.swing.JLabel LabelHospLoc;
    private javax.swing.JLabel LabelHospName;
    private javax.swing.JLabel NearbyLabel;
    private javax.swing.JPanel PatientPanel;
    private javax.swing.JButton PatientView;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JTextField TextCommunity;
    private javax.swing.JTextField TextHospComm;
    private javax.swing.JTextField TextHospLoc;
    private javax.swing.JTextField TextHospName;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton addEncounterButton;
    private javax.swing.JPanel addEncounterPanel;
    private javax.swing.JButton addPatientButton;
    private javax.swing.JPanel addPatientPanel;
    private javax.swing.JComboBox<String> comboHospLoc;
    private javax.swing.JLabel diagnosisLabel;
    private javax.swing.JLabel encounterBloodPressureLabel;
    private com.toedter.calendar.JDateChooser encounterDateField;
    private javax.swing.JLabel encounterDateLabel;
    private javax.swing.JTextArea encounterDiagnosisField;
    private javax.swing.JTextField encounterHeartField;
    private javax.swing.JLabel encounterHeartRateLabel;
    private javax.swing.JTextField encounterPatientIdField;
    private javax.swing.JLabel encounterPatientLabel;
    private javax.swing.JTextField encounterRespField;
    private javax.swing.JLabel encounterRespiratoryRateLabel;
    private javax.swing.JTextField encounterTemperatureField;
    private javax.swing.JLabel encounterTemperatureLabel;
    private javax.swing.JLabel encounterVitalSignLabel;
    private javax.swing.JLabel error;
    private javax.swing.JLabel errorAdmin;
    private javax.swing.JLabel errorEncounter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JButton newEncounterButton;
    private javax.swing.JLabel newPatientError;
    private javax.swing.JButton newPatientViewButton;
    private javax.swing.JTextField patientContactNoField;
    private javax.swing.JLabel patientContactNoLabel;
    private com.toedter.calendar.JDateChooser patientDobField;
    private javax.swing.JLabel patientDobLabel;
    private javax.swing.JTextField patientIdField;
    private javax.swing.JLabel patientIdLabel;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton viewPatientButton;
    private javax.swing.JPanel viewPatientPanel;
    private javax.swing.JTable viewPatientsTable;
    // End of variables declaration//GEN-END:variables
}
