/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author sid
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        SplitPane = new javax.swing.JSplitPane();
        TopPanel = new javax.swing.JPanel();
        PatientView = new javax.swing.JButton();
        DoctorView = new javax.swing.JButton();
        AdminView = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        PatientPanel = new javax.swing.JPanel();
        NearbyLabel = new javax.swing.JLabel();
        HospitalTable = new javax.swing.JScrollPane();
        HospitalDetails = new javax.swing.JTable();
        locationLabel = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        DoctorPanel = new javax.swing.JPanel();
        DocSplitPane = new javax.swing.JSplitPane();
        DocTopPanel = new javax.swing.JPanel();
        LabelDoctor = new javax.swing.JLabel();
        newPatientViewButton = new javax.swing.JButton();
        newEncounterButton = new javax.swing.JButton();
        viewPatientButton = new javax.swing.JButton();
        DocBotPanel = new javax.swing.JPanel();
        addPatientPanel = new javax.swing.JPanel();
        patientNameLabel = new javax.swing.JLabel();
        patientDobLabel = new javax.swing.JLabel();
        patientIdLabel = new javax.swing.JLabel();
        patientContactNoLabel = new javax.swing.JLabel();
        patientNameField = new javax.swing.JTextField();
        patientIdField = new javax.swing.JTextField();
        patientContactNoField = new javax.swing.JTextField();
        patientDobField = new com.toedter.calendar.JDateChooser();
        addPatientButton = new javax.swing.JButton();
        addEncounterPanel = new javax.swing.JPanel();
        encounterDateLabel = new javax.swing.JLabel();
        encounterVitalSignLabel = new javax.swing.JLabel();
        diagnosisLabel = new javax.swing.JLabel();
        encounterHeartField = new javax.swing.JTextField();
        encounterHeartRateLabel = new javax.swing.JLabel();
        encounterBloodPressureLabel = new javax.swing.JLabel();
        encounterTemperatureLabel = new javax.swing.JLabel();
        encounterRespiratoryRateLabel = new javax.swing.JLabel();
        encounterPatientLabel = new javax.swing.JLabel();
        encounterPatientIdField = new javax.swing.JTextField();
        EncounterBloodField = new javax.swing.JTextField();
        encounterTemperatureField = new javax.swing.JTextField();
        encounterRespField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        encounterDiagnosisField = new javax.swing.JTextArea();
        encounterDateField = new com.toedter.calendar.JDateChooser();
        addEncounterButton = new javax.swing.JButton();
        viewPatientPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        LabelAdmin = new javax.swing.JLabel();
        TextCommunity = new javax.swing.JTextField();
        LabelCommunity = new javax.swing.JLabel();
        ButtonCommunity = new javax.swing.JButton();
        LabelHospName = new javax.swing.JLabel();
        TextHospName = new javax.swing.JTextField();
        LabelHospLoc = new javax.swing.JLabel();
        TextHospLoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextHospComm = new javax.swing.JTextField();
        ButtonAddHosp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        PatientView.setText("Patient");

        DoctorView.setText("Doctor");

        AdminView.setText("Admin");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(PatientView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(DoctorView, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(AdminView, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientView)
                    .addComponent(DoctorView)
                    .addComponent(AdminView))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        SplitPane.setTopComponent(TopPanel);

        BottomPanel.setLayout(new java.awt.CardLayout());

        NearbyLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        NearbyLabel.setText("Nearby Hospitals");

        HospitalDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Location", "Community"
            }
        ));
        HospitalTable.setViewportView(HospitalDetails);

        locationLabel.setText("Enter Location :");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientPanelLayout = new javax.swing.GroupLayout(PatientPanel);
        PatientPanel.setLayout(PatientPanelLayout);
        PatientPanelLayout.setHorizontalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPanelLayout.createSequentialGroup()
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(NearbyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(locationLabel)
                        .addGap(81, 81, 81)
                        .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(HospitalTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        PatientPanelLayout.setVerticalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NearbyLabel)
                .addGap(54, 54, 54)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(HospitalTable, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        BottomPanel.add(PatientPanel, "card2");

        DocSplitPane.setDividerLocation(300);
        DocSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        DocTopPanel.setBackground(new java.awt.Color(204, 255, 255));

        LabelDoctor.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelDoctor.setText("Doctor Panel");

        newPatientViewButton.setText("Add new Patient");
        newPatientViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPatientViewButtonActionPerformed(evt);
            }
        });

        newEncounterButton.setText("Add new Encounter");

        viewPatientButton.setText("View Patient Details");

        javax.swing.GroupLayout DocTopPanelLayout = new javax.swing.GroupLayout(DocTopPanel);
        DocTopPanel.setLayout(DocTopPanelLayout);
        DocTopPanelLayout.setHorizontalGroup(
            DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocTopPanelLayout.createSequentialGroup()
                .addGroup(DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DocTopPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(newPatientViewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewPatientButton)
                        .addGap(52, 52, 52))
                    .addGroup(DocTopPanelLayout.createSequentialGroup()
                        .addGroup(DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newEncounterButton)
                            .addGroup(DocTopPanelLayout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(LabelDoctor)))
                        .addGap(0, 290, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DocTopPanelLayout.setVerticalGroup(
            DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocTopPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelDoctor)
                .addGap(7, 7, 7)
                .addGroup(DocTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPatientViewButton)
                    .addComponent(newEncounterButton)
                    .addComponent(viewPatientButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        DocSplitPane.setTopComponent(DocTopPanel);

        DocBotPanel.setLayout(new java.awt.CardLayout());

        patientNameLabel.setText("Name");

        patientDobLabel.setText("Date Of Birth");

        patientIdLabel.setText("Patient Id");

        patientContactNoLabel.setText("Contact No");

        patientIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdFieldActionPerformed(evt);
            }
        });

        addPatientButton.setText("Add New Patient");

        javax.swing.GroupLayout addPatientPanelLayout = new javax.swing.GroupLayout(addPatientPanel);
        addPatientPanel.setLayout(addPatientPanelLayout);
        addPatientPanelLayout.setHorizontalGroup(
            addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientPanelLayout.createSequentialGroup()
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPatientPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientIdLabel)
                            .addComponent(patientNameLabel)
                            .addComponent(patientDobLabel)
                            .addComponent(patientContactNoLabel))
                        .addGap(26, 26, 26)
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientDobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPatientPanelLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(addPatientButton)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        addPatientPanelLayout.setVerticalGroup(
            addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdLabel)
                    .addComponent(patientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNameLabel))
                .addGap(40, 40, 40)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientDobLabel)
                    .addComponent(patientDobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientContactNoLabel)
                    .addComponent(patientContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPatientButton)
                .addGap(39, 39, 39))
        );

        DocBotPanel.add(addPatientPanel, "card2");

        encounterDateLabel.setText("Date:");

        encounterVitalSignLabel.setText("Vital Sign:");

        diagnosisLabel.setText("Diagnosis:");

        encounterHeartField.setText("jTextField1");

        encounterHeartRateLabel.setText("HeartRate:");

        encounterBloodPressureLabel.setText("BloodPressure:");

        encounterTemperatureLabel.setText("Temperature:");

        encounterRespiratoryRateLabel.setText("Respiratory Rate:");

        encounterPatientLabel.setText("Patient Id:");

        EncounterBloodField.setText("jTextField1");

        encounterTemperatureField.setText("jTextField1");

        encounterRespField.setText("jTextField1");

        encounterDiagnosisField.setColumns(20);
        encounterDiagnosisField.setRows(5);
        jScrollPane1.setViewportView(encounterDiagnosisField);

        addEncounterButton.setText("Add Encounter");

        javax.swing.GroupLayout addEncounterPanelLayout = new javax.swing.GroupLayout(addEncounterPanel);
        addEncounterPanel.setLayout(addEncounterPanelLayout);
        addEncounterPanelLayout.setHorizontalGroup(
            addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEncounterPanelLayout.createSequentialGroup()
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEncounterPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEncounterPanelLayout.createSequentialGroup()
                                .addComponent(diagnosisLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEncounterPanelLayout.createSequentialGroup()
                                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encounterPatientLabel)
                                    .addComponent(encounterDateLabel)
                                    .addComponent(encounterVitalSignLabel))
                                .addGap(35, 35, 35)
                                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encounterDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(encounterPatientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(addEncounterPanelLayout.createSequentialGroup()
                        .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addEncounterPanelLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encounterHeartRateLabel)
                                    .addComponent(encounterBloodPressureLabel)
                                    .addComponent(encounterTemperatureLabel))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEncounterPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(encounterRespiratoryRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(encounterTemperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EncounterBloodField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encounterRespField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encounterHeartField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addEncounterPanelLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(addEncounterButton)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        addEncounterPanelLayout.setVerticalGroup(
            addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEncounterPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterPatientLabel)
                    .addComponent(encounterPatientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encounterDateLabel)
                    .addComponent(encounterDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(encounterVitalSignLabel)
                .addGap(27, 27, 27)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterHeartRateLabel)
                    .addComponent(encounterHeartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterBloodPressureLabel)
                    .addComponent(EncounterBloodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterTemperatureLabel)
                    .addComponent(encounterTemperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterRespiratoryRateLabel)
                    .addComponent(encounterRespField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diagnosisLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEncounterButton)
                .addGap(14, 14, 14))
        );

        DocBotPanel.add(addEncounterPanel, "card3");

        jLabel1.setText("Name:");

        javax.swing.GroupLayout viewPatientPanelLayout = new javax.swing.GroupLayout(viewPatientPanel);
        viewPatientPanel.setLayout(viewPatientPanelLayout);
        viewPatientPanelLayout.setHorizontalGroup(
            viewPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPatientPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addContainerGap(597, Short.MAX_VALUE))
        );
        viewPatientPanelLayout.setVerticalGroup(
            viewPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPatientPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        DocBotPanel.add(viewPatientPanel, "card4");

        DocSplitPane.setRightComponent(DocBotPanel);

        javax.swing.GroupLayout DoctorPanelLayout = new javax.swing.GroupLayout(DoctorPanel);
        DoctorPanel.setLayout(DoctorPanelLayout);
        DoctorPanelLayout.setHorizontalGroup(
            DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DocSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        DoctorPanelLayout.setVerticalGroup(
            DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DocSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        BottomPanel.add(DoctorPanel, "card3");

        LabelAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelAdmin.setText("Admin Controls");

        LabelCommunity.setText("Community Name");

        ButtonCommunity.setText("Add Community");

        LabelHospName.setText("Hospital Name");

        LabelHospLoc.setText("Hospital Location");

        jLabel2.setText("Hospital Community");

        ButtonAddHosp.setText("Add Hospital");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Location", "Hospital Community", "Modify"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonAddHosp)
                .addGap(245, 245, 245))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(LabelAdmin))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextCommunity)
                                    .addComponent(LabelCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                .addGap(89, 89, 89)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelHospLoc)
                                    .addComponent(jLabel2)
                                    .addComponent(LabelHospName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextHospName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextHospComm, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextHospLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAdmin)
                .addGap(30, 30, 30)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCommunity)
                    .addComponent(LabelHospName)
                    .addComponent(TextHospName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelHospLoc)
                    .addComponent(TextHospLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ButtonCommunity))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextHospComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addComponent(ButtonAddHosp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        BottomPanel.add(AdminPanel, "card4");

        SplitPane.setRightComponent(BottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(locationTextField.getText().isEmpty() || locationTextField.getText() == null)
        {
        JOptionPane.showMessageDialog(this, "Please enter a location!!!");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void patientIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdFieldActionPerformed

    private void newPatientViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPatientViewButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPatientViewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JButton AdminView;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton ButtonAddHosp;
    private javax.swing.JButton ButtonCommunity;
    private javax.swing.JPanel DocBotPanel;
    private javax.swing.JSplitPane DocSplitPane;
    private javax.swing.JPanel DocTopPanel;
    private javax.swing.JPanel DoctorPanel;
    private javax.swing.JButton DoctorView;
    private javax.swing.JTextField EncounterBloodField;
    private javax.swing.JTable HospitalDetails;
    private javax.swing.JScrollPane HospitalTable;
    private javax.swing.JLabel LabelAdmin;
    private javax.swing.JLabel LabelCommunity;
    private javax.swing.JLabel LabelDoctor;
    private javax.swing.JLabel LabelHospLoc;
    private javax.swing.JLabel LabelHospName;
    private javax.swing.JLabel NearbyLabel;
    private javax.swing.JPanel PatientPanel;
    private javax.swing.JButton PatientView;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JTextField TextCommunity;
    private javax.swing.JTextField TextHospComm;
    private javax.swing.JTextField TextHospLoc;
    private javax.swing.JTextField TextHospName;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton addEncounterButton;
    private javax.swing.JPanel addEncounterPanel;
    private javax.swing.JButton addPatientButton;
    private javax.swing.JPanel addPatientPanel;
    private javax.swing.JLabel diagnosisLabel;
    private javax.swing.JLabel encounterBloodPressureLabel;
    private com.toedter.calendar.JDateChooser encounterDateField;
    private javax.swing.JLabel encounterDateLabel;
    private javax.swing.JTextArea encounterDiagnosisField;
    private javax.swing.JTextField encounterHeartField;
    private javax.swing.JLabel encounterHeartRateLabel;
    private javax.swing.JTextField encounterPatientIdField;
    private javax.swing.JLabel encounterPatientLabel;
    private javax.swing.JTextField encounterRespField;
    private javax.swing.JLabel encounterRespiratoryRateLabel;
    private javax.swing.JTextField encounterTemperatureField;
    private javax.swing.JLabel encounterTemperatureLabel;
    private javax.swing.JLabel encounterVitalSignLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JButton newEncounterButton;
    private javax.swing.JButton newPatientViewButton;
    private javax.swing.JTextField patientContactNoField;
    private javax.swing.JLabel patientContactNoLabel;
    private com.toedter.calendar.JDateChooser patientDobField;
    private javax.swing.JLabel patientDobLabel;
    private javax.swing.JTextField patientIdField;
    private javax.swing.JLabel patientIdLabel;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton viewPatientButton;
    private javax.swing.JPanel viewPatientPanel;
    // End of variables declaration//GEN-END:variables
}
